---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphone
spec:
  replicas: 30
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 432258001168.dkr.ecr.us-east-1.amazonaws.com/tensure:latest
          ports:
            - containerPort: 8080

